services:
  gravifon:
    image: gravifon:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravifon
    ports:
      - "8080:8080"
    environment:
      GRAVIFON_LIBRARY_DIR: /music
      GRAVIFON_CONFIG_DIR: /config
    volumes:
      - ${GRAVIFON_LIBRARY_PATH:-gravifon-library}:/music:ro
      - ${GRAVIFON_CONFIG_PATH:-gravifon-config}:/config

volumes:
  gravifon-library:
  gravifon-config:
