spring:
  config:
    activate:
      on-profile: local

logging:
  structured:
    format:
      console: off
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n"

